app_name: we-mp-rss
cookie: 

#数据库连接 例如db:  mysql+pymysql://<username>:<password>@<host>/we-rss
db: ${DB:-sqlite:///db.db}

#通知
notice:
  dingding: "${DINGDING_WEBHOOK:-''}"

secret: ${SECRET_KEY:- 'we-mp-rss'}
token: 
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.39...

#定时任务执行间隔时间 单位秒 默认300s
interval: ${INTERVAL:- 300}