name: Docker Image Publish
on:
  push:
    branches:
      - main
    # paths:  # 仅在指定文件变化时触发（可选）
    #   # - 'ReadMe.md'
    #   - 'core/ver.py'
#   release:
#     types: [published]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.18.3' # 替换为你的项目所需的 Node.js 版本
      - name: Install dependencies
        run: |
          cd ./web_ui
          chmod +x build.sh
          ./build.sh
      - name: Copy to Static
        run: cp -r dist/* ../static

      - name: Log in to GHCR
        run: echo  ${{secrets.TOKEN}} | docker login ghcr.io -u  ${{github.actor}} --password-stdin
      - name: Sow env
        run: cat /home/runner/.docker/config.json    
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{github.repository}}:latest .
      - name: Push Docker Image
        run: docker push ghcr.io/${{github.repository}}:latest