name: Create Release
on:
  push:
    branches:
      - main
    paths:  # 仅在指定文件变化时触发（可选）
      - 'core/ver.py'
    # tags:
    #   - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN:  ${{secrets.TOKEN}}
        with:
          tag_name:  ${{github.ref}}
          release_name: Release  ${{github.ref}}
          draft: false
          prerelease: false
          files: |
            build/*.zip  # 指定上传的文件路径